config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :comittees

  resources :constituencies do
    get 'votes', on: :member
  end

  resources :voivodeships

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
  end
  

authenticated :user do
  root :to => 'voivodeships#index', as: :authenticated_root
end
root :to => 'welcome#index'

end

app/models/comittee.rb
class Comittee < ActiveRecord::Base
	has_and_belongs_to_many :voivodeships
	has_many :comittees, :through => :votes
	accepts_nested_attributes_for :comittees
	has_many :votes, :dependent => :destroy
	accepts_nested_attributes_for :votes


	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, 
						:default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/,
											  :size => { :in => 0..200.kilobytes }
	validates_presence_of :name, :voivodeship_ids
end

app/models/voivodeship.rb
class Voivodeship < ActiveRecord::Base
	has_many :constituencies, :dependent => :destroy
	has_and_belongs_to_many :comittees

	validates :name, :seats, :comittee_ids, presence: true
	validates :name, length: {minimum: 7}
	validates :seats, numericality:  {only_integer:true}

end

app/controllers/voivodeships_controller.rb
class VoivodeshipsController < ApplicationController
  before_action :set_voivodeship, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /voivodeships
  # GET /voivodeships.json
  def index
    @voivodeships = Voivodeship.all
  end

  # GET /voivodeships/1
  # GET /voivodeships/1.json
  def show
    if @voivodeship.constituencies.length == 0
      @assosciated_constituencies = "None"
    else 
      @assosciated_constituencies = @voivodeship.constituencies
      @con_ids = @assosciated_constituencies.pluck(:id)
    end
    if @voivodeship.comittees.length == 0
      @assosciated_comittees = "None"
    else 
      @assosciated_comittees = @voivodeship.comittees

    end

    
  end

  # GET /voivodeships/new
  def new
    @voivodeship = Voivodeship.new
  end

  # GET /voivodeships/1/edit
  def edit
  end

  # POST /voivodeships
  # POST /voivodeships.json
  def create
    @voivodeship = Voivodeship.new(voivodeship_params)

    respond_to do |format|
      if @voivodeship.save
        format.html { redirect_to @voivodeship, notice: 'Voivodeship was successfully created.' }
        format.json { render :show, status: :created, location: @voivodeship }
      else
        format.html { render :new }
        format.json { render json: @voivodeship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voivodeships/1
  # PATCH/PUT /voivodeships/1.json
  def update
    respond_to do |format|
      if @voivodeship.update(voivodeship_params)
        format.html { redirect_to @voivodeship, notice: 'Voivodeship was successfully updated.' }
        format.json { render :show, status: :ok, location: @voivodeship }
      else
        format.html { render :edit }
        format.json { render json: @voivodeship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voivodeships/1
  # DELETE /voivodeships/1.json
  def destroy
    @voivodeship.destroy
    respond_to do |format|
      format.html { redirect_to voivodeships_url, notice: 'Voivodeship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voivodeship
      @voivodeship = Voivodeship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voivodeship_params
      params.require(:voivodeship).permit(:name, :seats, :comittee_ids => [])
    end
end

app/helpers/voivodeships_helper.rb
module VoivodeshipsHelper
end

app/views/voivodeships/_form.html.erb
<%= form_for(@voivodeship) do |f| %>
  <% if @voivodeship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voivodeship.errors.count, "error") %> prohibited this voivodeship from being saved:</h2>

      <ul>
      <% @voivodeship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :seats %><br>
    <%= f.number_field :seats %>
  </div>
    <div class="field">
  <%= f.collection_select :comittee_ids, Comittee.all, :id, :name, {}, {:multiple => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/voivodeships/edit.html.erb
<h1>Editing Voivodeship</h1>

<%= render 'form' %>

<%= link_to 'Show', @voivodeship %> |
<%= link_to 'Back', voivodeships_path %>

app/views/voivodeships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Voivodeships</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voivodeships.each do |voivodeship| %>
      <tr>
        <td><%= voivodeship.name %></td>
        <td><%= link_to 'Show', voivodeship %></td>
        <% if can? :update, voivodeship %>
          <td><%= link_to 'Edit', edit_voivodeship_path(voivodeship) %></td>
        <% end %>
        <% if can? :destroy, voivodeship %>
          <td><%= link_to 'Destroy', voivodeship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @voivodeships %>
  <%= link_to 'New Voivodeship', new_voivodeship_path %>
<% end %>

app/views/voivodeships/new.html.erb
<h1>New Voivodeship</h1>

<%= render 'form' %>

<%= link_to 'Back', voivodeships_path %>

app/views/voivodeships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @voivodeship.name %>
</p>
<p>
<p>
  <strong>Seats:</strong>
  <%= @voivodeship.seats %>
</p>
<p>
  <strong>Constituencies:</strong>
  <% if @assosciated_constituencies != "None" %>
    <% @assosciated_constituencies.each do |c| %>
    	<li><%= link_to c.name, c %></li>
    <% end %>
  <% end %>
</p>
<p>
  <strong>Comittees:</strong>
  <% if @assosciated_comittees != "None" %>

    <% @assosciated_comittees.each do |c| %>
    	<li><%= link_to c.name, c %> - <%= c.votes.where(:constituency_id => (@con_ids)).sum(:quantity) %> votes</li>
    <% end %>

  <% end %>
</p>

<%= link_to 'Edit', edit_voivodeship_path(@voivodeship) %>
<%= link_to 'Back', voivodeships_path %>