config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :comittees

  resources :constituencies do
    get 'votes', on: :member
  end

  resources :voivodeships

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
  end
  

authenticated :user do
  root :to => 'voivodeships#index', as: :authenticated_root
end
root :to => 'welcome#index'

end

app/models/constituency.rb
class Constituency < ActiveRecord::Base
  belongs_to :voivodeship
  has_many :comittees, :through => :votes
  has_many :users
  has_many :votes, :dependent => :destroy
  accepts_nested_attributes_for :votes
  accepts_nested_attributes_for :comittees

  validate :sum_of_votes

  def sum_of_votes
  	if self.votes.map(&:quantity).sum > self.voters
  		errors.add(:quantity, " of votes exceeds number of voters")
  	end
  end
end

app/controllers/constituencies_controller.rb
class ConstituenciesController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!

  # GET /constituencies
  # GET /constituencies.json
  def index
    
  end

  # GET /constituencies/1
  # GET /constituencies/1.json
  def show

  end

  # GET /constituencies/new
  def new

  end

  # GET /constituencies/1/edit
  def edit
    @constituency.votes.build
  end

  # POST /constituencies
  # POST /constituencies.json
  def create

    respond_to do |format|
      if @constituency.save
        format.html { redirect_to @constituency, notice: 'Constituency was successfully created.' }
        format.json { render :show, status: :created, location: @constituency }
      else
        format.html { render :new }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /constituencies/1
  # PATCH/PUT /constituencies/1.json
  def update
    respond_to do |format|
      if @constituency.update(constituency_params)
        format.html { redirect_to @constituency, notice: 'Constituency was successfully updated.' }
        format.json { render :show, status: :ok, location: @constituency }
      else
        format.html { render :edit }
        format.json { render json: @constituency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /constituencies/1
  # DELETE /constituencies/1.json
  def destroy
    @constituency.destroy
    respond_to do |format|
      format.html { redirect_to constituencies_url, notice: 'Constituency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def votes
    @comittees = @constituency.voivodeship.comittees.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.


    # Never trust parameters from the scary internet, only allow the white list through.
    def constituency_params
      params.require(:constituency).permit(:name, :voters, :voivodeship_id, :comittee_attributes, votes_attributes: [ :id, :comittee_id, :constituency_id, :quantity ])
    end
end

app/helpers/constituencies_helper.rb
module ConstituenciesHelper
	def selectVoivod
		Voivodeship.all.each do |voi|
			voids = voi.name
		end
	end
end

app/views/constituencies/_form.html.erb
<%= form_for @constituency, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :voters %><br>
    <%= f.number_field :voters %>
  </div>
  <div class="field">
    <%= f.label :voivodeship_id %><br>
    <%= f.collection_select(:voivodeship_id, Voivodeship.all, :id, :name) %>
  </div>
  <% if current_user.constituency_id == @constituency.id and !@constituency.voivodeship.blank? %>
    <% @constituency.voivodeship.comittees.each do |comittee| %>
      <%= f.fields_for :votes, @constituency.votes.find_or_initialize_by(constituency_id: @constituency.id, comittee_id: comittee.id) do |v| %>
        <%= v.label comittee.name %>
        <%= v.hidden_field :comittee_id, :value => comittee.id %>
        <%= v.hidden_field :constituency_id, :value => @constituency.id %>
        <%= v.number_field :quantity %>

      <% end %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/constituencies/edit.html.erb
<h1>Editing Constituency</h1>

<%= render 'form' %>

<%= link_to 'Show', @constituency %> |
<%= link_to 'Back', constituencies_path %>

app/views/constituencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Constituencies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Voters</th>
      <th>Voivodeship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @constituencies.each do |constituency| %>
      <tr>
        <td><%= constituency.name %></td>
        <td><%= constituency.voters %></td>
        <td><%= constituency.voivodeship.name %></td>
        <td><%= link_to 'Show', constituency %></td>
        <% if can? :update, constituency %>
          <td><%= link_to 'Edit', edit_constituency_path(constituency) %></td>
        <% end %>
        <% if can? :destroy, constituency %>
          <td><%= link_to 'Destroy', constituency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, @constituencies %>
  <%= link_to 'New Constituency', new_constituency_path %>
<% end %>

app/views/constituencies/new.html.erb
<h1>New Constituency</h1>

<%= render 'form' %>

<%= link_to 'Back', constituencies_path %>

app/views/constituencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @constituency.name %>
</p>

<p>
  <strong>Voters:</strong>
  <%= @constituency.voters %>
</p>

<p>
  <strong>Voivodeship:</strong>
  <%= link_to @constituency.voivodeship.name, @constituency.voivodeship %>
</p>

<p>
  <strong>Votes:</strong>
  <% @constituency.votes.each do |v| %>
  <li><%= link_to v.comittee.name, v.comittee %> <%= v.quantity %>
  	<% end %>
</p>

<%= link_to 'Edit', edit_constituency_path(@constituency) %> |
<%= link_to 'Back', constituencies_path %>

app/views/constituencies/votes.html.erb
<%= form_for(@constituency) do |f| %>
  <% if @constituency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@constituency.errors.count, "error") %> prohibited this constituency from being saved:</h2>

      <ul>
      <% @constituency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% @comittees.each do |comittee| %>

      <%= f.fields_for :votes, vote do |v| %>
        <%= v.label comittee.name %>
        <%= v.hidden_field :comittee_id, :value => comittee.id %>
        <%= comittee.id %>
        <%= v.number_field :quantity %>

      <% end %>
    <% end %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>