config/routes.rb
Rails.application.routes.draw do
  resources :votes

  resources :comittees

  resources :constituencies do
    get 'votes', on: :member
  end

  resources :voivodeships

  devise_for :users
  scope "/admin" do
    resources :users
    resources :roles
  end
  

authenticated :user do
  root :to => 'voivodeships#index', as: :authenticated_root
end
root :to => 'welcome#index'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Vote Count", root_path, id: "logo" %></li>
        <% if current_user.try(:admin?) %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Roles", roles_path %></li>
          <% end %>
        <li><%= link_to "Voivodeship",   voivodeships_path %></li>
        <li><%= link_to "Constituency",   constituencies_path %></li>
        <li><%= link_to "Comittee", comittees_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
			  
			  <li><%= link_to "Edit profile", edit_user_registration_path %></li>
			  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
        <li><%= current_user.email %></li>
			<% else %>
			  <li><%= link_to "Sign up", new_user_registration_path %></li> <li><%= link_to "sign in", new_user_session_path %></li>
			<% end %>
       </ul>
			<% flash.each do |name, msg| %>
			  <%= content_tag :div, msg, id: "flash_#{name}" %>
			<% end %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoteCount</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
	</div>

</body>
</html>